### ISSUE TITLE
System.Exception when scraping schedule

### ISSUE THREAD

**Issue by bigduck123** [JustBrandonLim/TimetableGrabber-SIT#1]
log says Exception of type 'System.Exception' was thrown

**Comment by JustBrandonLim** [comment]
Hello, I am aware of this issue, but I can't seem to replicate it on my side.  Are you able to provide more information such as your Windows Region Settings.

Windows 10:
![image](https://user-images.githubusercontent.com/93673724/150186733-84afce3d-aaf9-47c1-a8b9-514f15bf7057.png)

Windows 11:
![image](https://user-images.githubusercontent.com/93673724/150186800-006b2cb8-bc0d-4672-88e9-52149d57a62b.png)

**Comment by JustBrandonLim** [comment]
I have found the issue, please ensure your `Regional format data` is English (Singapore). Please let me know if it works for you.

**Comment by JustBrandonLim** [comment]
Issue should be solved. Closed, no reply from user.
