### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Muhd-Naufal** [JustBrandonLim/TimetableGrabber-SIT#3]
![Capture](https://user-images.githubusercontent.com/51323038/186704265-c94698ce-4976-4b73-981f-d32ba606ab20.PNG)

I got this error message. Please advise.

**Comment by JustBrandonLim** [comment]
Hi, from the screenshot you have attached, it seems that you do not have the correct version of chromedriver installed.

Please check your google chrome's version and download the correct chromedriver from [here](https://chromedriver.chromium.org/downloads), and place it in the same folder as the application!

**Comment by Muhd-Naufal** [comment]
Ah, I didn't place it in the same folder. But now I have a new error: 

![Capture2](https://user-images.githubusercontent.com/51323038/186849048-6e5cd889-8ee5-44f5-8db8-4636b116948f.PNG)
:

Full Error Message:

[3:36 PM]: Clicking "Course Management"...
[3:36 PM]: Closing Chrome...
[3:36 PM]: Closed Chrome...
[3:36 PM]: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@onclick, 'https://in4sit.singaporetech.edu.sg/psc/CSSISSTD_newwin/EMPLOYEE/SA/c/NUI_FRAMEWORK.PT_AGSTARTPAGE_NUI.GBL?CONTEXTIDPARAMS=TEMPLATE_ID%3aPTPPNAVCOL&scname=ADMN_MODULE_MANAGEMENT&PTPPB_GROUPLET_ID=N_SR_MODULE_MATTERS&CRefName=ADMN_NAVCOLL_18&AJAXTRANSFER=Y')]"}
  (Session info: headless chrome=104.0.5112.102)

**Comment by JustBrandonLim** [comment]
Did you try rerunning again? Seems to work fine on my side. Are you from a joint degree course by any chance?

**Comment by Muhd-Naufal** [comment]
Ah, I guess after closing every programme and maybe a pc restart fixed it. It works now and yes I'm from a joint degree course. Thanks so much!!

**Comment by JustBrandonLim** [comment]
> Ah, I guess after closing every programme and maybe a pc restart fixed it. It works now and yes I'm from a joint degree course. Thanks so much!!

Welcome!
