### ISSUE TITLE
Object reference not set  in an instance of an object 

### ISSUE THREAD

**Issue by wheks** [JustBrandonLim/TimetableGrabber-SIT#7]
Hi there not really technical savvy here but i cant seem to be able to export the calendar i face the issue mentioned in  the title everytime i try to run the programme

**Comment by wheks** [comment]
![image](https://user-images.githubusercontent.com/115719064/195617969-7319f742-387d-444f-b9cf-7fd316372b34.png)

**Comment by JustBrandonLim** [comment]
Did you download and place the correct version of chromedriver in the the same folder?
